### PR TITLE
add bib and ris

### PR DESCRIPTION
**Pull request by spiwokv**
I just added RIS and BibTeX files and links to them for easier citing. Thanks to Petra Rubesova for testing RIS files.

### CODE REVIEW

**Comment by maxbonomi** [comment]
I cannot merge this pull request. The website is built automatically from another GitHub repository. Please send me via email only the ID of the egg and the doi, and I will update your egg!

**Comment by spiwokv** [comment]
I didn't know that. It is not about egg, I have just added bib and ris files for the Nature Methods paper for easier citing ;-)
https://github.com/spiwokv/plumed-nest.github.io/blob/master/cite.md

**Comment by maxbonomi** [comment]
Ok, please then have a look at this GitHub where we actually push things:

https://github.com/plumed-nest/plumed-nest

**Comment by spiwokv** [comment]
Sorry, I will fix it.
V.

**Comment by maxbonomi** [comment]
No problem!!!

**Pull request closed without merging**
